#
# Project:
# Module:	
# Programmer:   Brandon Tarney
# Organization:	JHU EP
# Host System:	SunOS 4
# Date Created: May 5, 2017
# Modifications:
#	$Log$
# 
# 

# Library to make (eg: libeg.a)
LIBRARY = libshared_memory.a


# Source files for LIBRARY routines
SRC	= shared_memory.c

# Master include files for libraries.
include ../../../Make_templates/Make.lib
